version: '3'

services:
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./etc/traefik:/etc/traefik"
      - "./logs:/var/log/traefik"

networks:
  default:
    external:
      name: docker_default
